### PR TITLE
Restore SBN_QGSP_BERT_NNC to be QGSP_BERT with no neutron cut

### PR DESCRIPTION
**Pull request by marcodeltutto**
This PR restores the `SBN_QGSP_BERT_NNC` physics list to be "`QGSP_BERT` with no neutron cut".
Two separate PRs should follow, one for SBND and one for ICARUS, where the `QGSP_BERT_HP` physics list is adopted:

- [x] SBND: https://github.com/SBNSoftware/sbndcode/pull/468
- [ ] ICARUS: https://github.com/SBNSoftware/icaruscode/pull/737

See issue #453 for more details.

### CODE REVIEW

**Comment by jzettle** [comment]
Hi @marcodeltutto, thanks for this. Is the idea we need to change https://github.com/SBNSoftware/icaruscode/blob/ffa6d4167b9d44f86c1e79300e1c646c4eb730ce/fcl/g4/larg4_services_icarus.fcl#L11 to "QGSP_BERT_HP"? I'm trying to understand which would become the default in that case, what is written in sbncode or what is written in icaruscode/sbndcode? I can try to make this change later today I have a couple other things to do before I can get to this and do the same comparison test that you did

**Comment by marcodeltutto** [comment]
Thanks, @jzettle! Yes, I believe the only thing to be changed is that one.

The default is what is specified in `PhysicsListName` for SBND and ICARUS. In `sbncode` there is no default, but we can add custom physics lists in `sbncode/LArG4/PhysicsLists/` and then point to them in `sbndcode` and `icaruscode`.

In the future, we can think about moving `larg4_services_icarus.fcl` and `larg4_services_sbnd.fcl` to `sbncode` so we both use the same config.

**Comment by jzettle** [comment]
Thanks Marco! Sounds good, I wanted to better understand the idea of this change. I agree we should figure out how to at some point move truly common pieces of the simulation to sbncode so it is more synchronized between the two detector simulations

**Comment by jzettle** [comment]
@marcodeltutto I created https://github.com/SBNSoftware/icaruscode/pull/737 to address the same as you did on sbndcode and edited your initial post to include that. Looks like it is making the intended change when comparing the old and new versions and what Geant4 is loading looking at the neutron as a comparison

**Comment by marcodeltutto** [comment]
Sounds great, thanks @jzettle!

**Comment by ibsafa** [comment]
@cerati @sjgardiner Do we want this physics list update in the next production campaign? If so, we need folks to approve this PR ASAP. sbndcode already has this change merged. icaruscode also has a similar PR that is already approved, but not merged. Thanks!

**Review by jzettle — APPROVED** [review]
With the other SBND and ICARUS PRs combined mentioned in Marco's initial comment with this one it looks good. Apologies I thought I had approved this at some point

**Pull request merged**
