### PR TITLE
Feature/howard for dev incorporate gputnam trigger product change

### PR DESCRIPTION
**Pull request by brucehoward-physics**
Equivalent of the commit in https://github.com/SBNSoftware/sbncode/pull/431 to fill the extra SRTrigger info as in https://github.com/SBNSoftware/sbnanaobj/pull/126, which as noted over there is a copy of commits initially from @gputnam with the linked PR being for the NuMI reprocessing release. This is for develop.

This depends on https://github.com/SBNSoftware/sbnanaobj/pull/129

This also works in the suggestions from @PetrilloAtWork on that linked PR.

NOTE I didn't do any testing with this exact PR just built it.

### CODE REVIEW

**Review by PetrilloAtWork — APPROVED** [review]
Approved, and thank you for taking care of this.

**Comment by ibsafa** [comment]
trigger build

**Comment by ibsafa** [comment]
trigger build SBNSoftware/sbnanaobj/#129

**Comment by ibsafa** [comment]
trigger build SBNSoftware/sbnanaobj/#129

**Pull request merged**
