### PR TITLE
Add larcv2 dependency + Supera as a git submodule

### PR DESCRIPTION
**Pull request by Temigo**
This PR is part of an effort from the ICARUS ML group to merge our pipeline back into the official production workflow.

* Add `larcv2` dependency in `ups/product_deps` because Supera needs it
* Add `Supera` as a git submodule to make it available to both ICARUS and SBND. Supera is a LArSoft module (and several LArCV modules) that 1. makes truth labels for ML-based reconstruction purpose and 2. produces a LArCV file (input format of the ML-based reconstruction chain) from LArsoft products.

**What needs to happen before this can be merged:**
1. `mrb gitCheckout` currently does not initialize nor update git submodules. I submitted a separate PR [here](https://github.com/art-framework-suite/mrb/pull/12) to make it initialize submodules by default.

3. I will update this PR with a commit for the latest Supera version once [this PR](https://github.com/DeepLearnPhysics/Supera/pull/8) (changes to work with SEDLite) is merged. These changes will be needed to run Supera as part of the official workflow.

### CODE REVIEW

**Comment by Temigo** [comment]
@miquelnebot  @SFBayLaser The PR in `lardataobj` and the PR in `mrb` were both merged, so I can open this one for review. Here are the caveats or points of discussion where I would like your feedback:

1. Supera will be included as a git submodule. As mentioned in meetings, `mrb` developers added the `--recurse-submodules` option to `mrb gitCheckout`, but this is only true for **sbncode cloned from SBNSoftware**. Any attempt to clone `sbnocde` from a fork will result in submodules not being initialized from `mrb gitCheckout`. Hence I added a word of warning in the README. Feel free to disagree if you think that note should be elsewhere.
2. I am not sure how to deal with fhicl files organization. We have a `job` folder in Supera ([see here](https://github.com/DeepLearnPhysics/Supera/tree/icarus/job)) which has quite a few fhicl files that we use regularly for our own small scale productions, but that will not be needed for SBN production. All the fhicl files needed for production are in `job/include` folder. Do you care about including the other non-essential fhicl files? Can I somehow put them all into a subfolder in the `localProducts` fhicl folder for a cleaner look? Let me know your thoughts.
3. Of course, just like #286 this PR depends on larsoft v09_60_00 in case you want to test it out.

**Comment by Temigo** [comment]
trigger build https://github.com/LArSoft/lardataobj/pull/32

**Comment by Temigo** [comment]
@miquelnebot As mentioned in the other PR I don't think I can assign reviewers (permission issue). This change (for both PRs) has been presented and discussed in the SBN Infrastructure meeting two times so far. The latest document on it is [here](https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=27739), docdb id 27739.

**Comment by Temigo** [comment]
trigger build

**Comment by Temigo** [comment]
@miquelnebot @SFBayLaser I corrected this PR so it passes the CI checks. Could you please assign a reviewer for me? I cannot do it myself (not a member). Thanks!

**Review by wesketchum — COMMENTED** [review]
Now that I'm seeing this, I'm growing a tiny bit worried ...

Is there a reason that we shouldn't be packaging Supera as its own ups product? And pull in the dependencies properly that way?

I'll try to find the presentation with this information again, but I'm a little hesitant that compiling this into sbncode as a whole is the most sustainable. @cerati should maybe also comment more specifically how this may change as we think about moving to spack.

**Comment by wesketchum** [comment]
Just to be clear: this may be the best path forward for the moment, but I'm just a little worried about how this evolves. Reading the presentation from @Temigo again, it's clear to me that I don't understand the dependency structure of Supera in this to really know what would be the best solution long-term (if it's not this).

**Review by SFBayLaser — APPROVED** [review]
I am not sure I am expert enough on the updates to mrb to comment on the operation of submodules. I note that the build/CI tests pass though they probably don't test actually running supera. Since this looks good to me mechanically I think we should move forward with it and then try to make sure it is thoroughly tested as soon as the release is out.

**Comment by jzennamo** [comment]
Sorry all, I think I missed being assigned this review...

Big picture, looking over this it seems to create a "supera" submodule, is there a reason that this isn't made it's own stand-alone package and letting ups deal with the dependencies? I think that is the more common handling, but I am happy to be educated why this method is better

**Comment by wesketchum** [comment]
OK, so we met as a group yesterday, and I think the plan forward here is this:

- Approve this pull request for now, in order to be able to push forward on integration of this workflow. (Next steps are to work with @SFBayLaser on fhicl files to get this running in the new release)
- For the next release, make a plan for refashioning the dependency. We discussed two options:
-- Simply make the supera directory a part of `sbncode` (or other appropriate `larsoft` package) without utilizing git submodules for 'production' releases, and work through a developers' workflow to allow for integration/testing of changes that can then be deployed. Developers' workflow sounds fancy, but it could be as simple as just copying things from one place to another.
-- Refactor into its own package, which means making a ups product for now and a spack product(?) for the future. We can solicit help for the build/packaging/distribution mechanics there. This may involve some refactoring to split algorithm/non-larsoft libraries from the framework ones (in which case, module/framework code may live in sbncode).

I'll make a new issue to track this new work.

**Review by wesketchum — APPROVED** [review]

**Pull request merged**
