### PR TITLE
Calibration NTuple Update

### PR DESCRIPTION
**Pull request by gputnam**
Refine truth matching variables; add in SCE corrected versions where useful; add in an addition Hit truth backtracking method.

Depends on https://github.com/SBNSoftware/sbnobj/pull/33.

### CODE REVIEW

**Comment by gputnam** [comment]
PR should be good to go!

**Review by wesketchum — APPROVED** [review]
Looks ok to me.

**Comment by gputnam** [comment]
I have looked at the errors. AFAICT, they seem to be caused by some CORSIKA files not being read correctly. 

For example:
`77: dd: error reading '/cvmfs/sbn.osgstorage.org/pnfs/fnal.gov/usr/sbn/persistent/stash/physics/cosmics/Fermilab/CORSIKA/standard/v01_00/p_showers_085086.db': Input/output error`

I don't think these errors actually represent a problem with the code.

**Comment by gputnam** [comment]
Just did!

**Pull request merged**
