### PR TITLE
Feature/altflatcaf

### PR DESCRIPTION
**Pull request by cjbackhouse**
Use the new ability of srproxy v00.16 to generate FlatRecord, reducing code duplication.
Small adjustments to the srproxy interface allow reading regular cafs, old flatcafs, and new flatcafs.
check_proxy.C confirms everything is working as expected.

### CODE REVIEW

**Comment by wesketchum** [comment]
@cjbackhouse I can't get this to build with c7:prof. Can you take a look?

**Comment by cjbackhouse** [comment]
I was just trying to figure out how to ask for a CI build, since this is the sort of thing compilers are likely to be picky about.

Can you point me to some logs?

**Comment by wesketchum** [comment]
was just doing it all locally. Here's what I have ...

```
[ 13%] Copying /icarus/app/users/wketchum/sbncode_build_areas/v09_10_01/srcs/sbncode/sbncode/LArRecoProducer/crtmatch_producer.fcl to /icarus/app/users/wketchum/sbncode_build_areas/v09_10_01/build_slf7.x86_64/sbncode/fcl/crtmatch_producer.fcl
[ 14%] Building CXX object sbncode/sbncode/StandardRecord/CMakeFiles/StandardRecord.dir/SRCRTHit.cxx.o
[ 14%] Built target +sbncode+fcl+crtmatch_producer.fcl
[ 14%] Building CXX object sbncode/sbncode/StandardRecord/CMakeFiles/StandardRecord.dir/SRCRTHitMatch.cxx.o
INFO Parsing source file "/icarus/app/users/wketchum/sbncode_build_areas/v09_10_01/srcs/sbncode/sbncode/StandardRecord/StandardRecord.h" ... 
INFO Parsing source file "/icarus/app/users/wketchum/sbncode_build_areas/v09_10_01/srcs/sbncode/sbncode/StandardRecord/StandardRecord.h" ... 
[ 14%] Building CXX object sbncode/sbncode/OpDet/CMakeFiles/sbncode_OpDet_PDMapAlgSimple_tool.dir/PDMapAlgSimple_tool.cc.o
[ 14%] Building CXX object sbncode/sbncode/CAFMaker/RecoUtils/CMakeFiles/caf_RecoUtils.dir/RecoUtils.cc.o
[ 15%] Linking CXX shared library ../../../lib/libsbnobj_SBND_CRT.so
Scanning dependencies of target sbn_LArReco
In file included from /icarus/app/users/wketchum/sbncode_build_areas/v09_10_01/srcs/sbncode/sbncode/StandardRecord/StandardRecord.h:10:
In file included from /icarus/app/users/wketchum/sbncode_build_areas/v09_10_01/srcs/sbncode/sbncode/StandardRecord/SRCRTHit.h:7:
In file included from /icarus/app/users/wketchum/sbncode_build_areas/v09_10_01/srcs/sbncode/sbncode/StandardRecord/SRVector3D.h:9:
In file included from /cvmfs/larsoft.opensciencegrid.org/products/root/v6_18_04d/Linux64bit+3.10-2.17-c7-prof/include/TVector3.h:14:
In file included from /cvmfs/larsoft.opensciencegrid.org/products/root/v6_18_04d/Linux64bit+3.10-2.17-c7-prof/include/TError.h:29:
In file included from /cvmfs/larsoft.opensciencegrid.org/products/root/v6_18_04d/Linux64bit+3.10-2.17-c7-prof/include/Rtypes.h:29:
In file included from /cvmfs/larsoft.opensciencegrid.org/products/clang/v7_0_0/Linux64bit+3.10-2.17/bin/../include/c++/v1/atomic:544:
In file included from /cvmfs/larsoft.opensciencegrid.org/products/clang/v7_0_0/Linux64bit+3.10-2.17/bin/../include/c++/v1/cstddef:110:
/cvmfs/larsoft.opensciencegrid.org/products/clang/v7_0_0/Linux64bit+3.10-2.17/bin/../include/c++/v1/type_traits:740:56: error: use of undeclared
      identifier '_Float16'
In file included from /icarus/app/users/wketchum/sbncode_build_areas/v09_10_01/srcs/sbncode/sbncode/StandardRecord/StandardRecord.h:10:
In file included from /icarus/app/users/wketchum/sbncode_build_areas/v09_10_01/srcs/sbncode/sbncode/StandardRecord/SRCRTHit.h:7:
template <>          struct __libcpp_is_floating_point<_Float16>    : public true_type {};
                                                       ^
In file included from /icarus/app/users/wketchum/sbncode_build_areas/v09_10_01/srcs/sbncode/sbncode/StandardRecord/SRVector3D.h:9:
In file included from /cvmfs/larsoft.opensciencegrid.org/products/root/v6_18_04d/Linux64bit+3.10-2.17-c7-prof/include/TVector3.h:14:
In file included from /cvmfs/larsoft.opensciencegrid.org/products/root/v6_18_04d/Linux64bit+3.10-2.17-c7-prof/include/TError.h:29:
In file included from /cvmfs/larsoft.opensciencegrid.org/products/root/v6_18_04d/Linux64bit+3.10-2.17-c7-prof/include/Rtypes.h:29:
In file included from /cvmfs/larsoft.opensciencegrid.org/products/clang/v7_0_0/Linux64bit+3.10-2.17/bin/../include/c++/v1/atomic:544:
In file included from /cvmfs/larsoft.opensciencegrid.org/products/clang/v7_0_0/Linux64bit+3.10-2.17/bin/../include/c++/v1/cstddef:110:
/cvmfs/larsoft.opensciencegrid.org/products/clang/v7_0_0/Linux64bit+3.10-2.17/bin/../include/c++/v1/type_traits:740:56: error: use of undeclared
      identifier '_Float16'
template <>          struct __libcpp_is_floating_point<_Float16>    : public true_type {};
                                                       ^
[ 15%] Building CXX object sbncode/sbncode/OscLib/CMakeFiles/OscLib.dir/EarthModel.cxx.o
Scanning dependencies of target +sbncode+fcl+transfer_flasht0_producer.fcl
[ 15%] Copying /icarus/app/users/wketchum/sbncode_build_areas/v09_10_01/srcs/sbncode/sbncode/LArRecoProducer/transfer_flasht0_producer.fcl to /icarus/app/users/wketchum/sbncode_build_areas/v09_10_01/build_slf7.x86_64/sbncode/fcl/transfer_flasht0_producer.fcl
[ 15%] Linking CXX shared library ../../lib/libsbndaq-artdaq-core_BuildInfo.so
[ 15%] Built target +sbncode+fcl+transfer_flasht0_producer.fcl
[ 15%] Built target sbnobj_SBND_CRT
[ 15%] Building CXX object sbncode/sbncode/StandardRecord/CMakeFiles/StandardRecord.dir/SRCRTTrack.cxx.o
[ 16%] Building CXX object sbncode/sbncode/OscLib/CMakeFiles/OscLib.dir/IOscCalculator.cxx.o
[ 16%] Building CXX object sbncode/sbncode/FlashMatch/CMakeFiles/sbncode_FlashMatch_FlashPredict_module.dir/FlashPredict_module.cc.o
[ 16%] Linking CXX shared library ../../../lib/libsbnobj_Common_Reco.so
[ 16%] Linking CXX shared library ../../../lib/libsbnobj_Common_CRT.so
[ 16%] Built target sbndaq-artdaq-core_BuildInfo
[ 16%] Building CXX object sbncode/sbncode/OscLib/CMakeFiles/OscLib.dir/OscCalculator.cxx.o
[ 16%] Built target sbnobj_Common_CRT
[ 16%] Building CXX object sbncode/sbncode/OscLib/CMakeFiles/OscLib.dir/OscCalculatorCPT.cxx.o
1 error generated.
Traceback (most recent call last):
  File "/cvmfs/sbn.opensciencegrid.org/products/sbn/srproxy/v00.16//bin/gen_srproxy", line 475, in <module>
    main()
  File "/cvmfs/sbn.opensciencegrid.org/products/sbn/srproxy/v00.16//bin/gen_srproxy", line 433, in main
    decls = pygccxml.parser.parse([input_header], config)
  File "/cvmfs/larsoft.opensciencegrid.org/products/pygccxml/v1_9_1b/lib/python3.7/site-packages/pygccxml-1.9.1-py3.7.egg/pygccxml/parser/__init__.py", line 51, in parse
  File "/cvmfs/larsoft.opensciencegrid.org/products/pygccxml/v1_9_1b/lib/python3.7/site-packages/pygccxml-1.9.1-py3.7.egg/pygccxml/parser/project_reader.py", line 264, in read_files
  File "/cvmfs/larsoft.opensciencegrid.org/products/pygccxml/v1_9_1b/lib/python3.7/site-packages/pygccxml-1.9.1-py3.7.egg/pygccxml/parser/project_reader.py", line 292, in __parse_file_by_file
  File "/cvmfs/larsoft.opensciencegrid.org/products/pygccxml/v1_9_1b/lib/python3.7/site-packages/pygccxml-1.9.1-py3.7.egg/pygccxml/parser/source_reader.py", line 356, in read_file
  File "/cvmfs/larsoft.opensciencegrid.org/products/pygccxml/v1_9_1b/lib/python3.7/site-packages/pygccxml-1.9.1-py3.7.egg/pygccxml/parser/source_reader.py", line 375, in read_cpp_source_file
  File "/cvmfs/larsoft.opensciencegrid.org/products/pygccxml/v1_9_1b/lib/python3.7/site-packages/pygccxml-1.9.1-py3.7.egg/pygccxml/parser/source_reader.py", line 324, in create_xml_file
RuntimeError: Error occurred while running CASTXML:  status:1
[ 16%] Built target sbnobj_Common_Reco
1 error generated.
make[2]: *** [sbncode/sbncode/FlatMaker/FlatRecord.cxx] Error 1
make[1]: *** [sbncode/sbncode/FlatMaker/CMakeFiles/FlatMaker.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Traceback (most recent call last):
  File "/cvmfs/sbn.opensciencegrid.org/products/sbn/srproxy/v00.16//bin/gen_srproxy", line 475, in <module>
    main()
  File "/cvmfs/sbn.opensciencegrid.org/products/sbn/srproxy/v00.16//bin/gen_srproxy", line 433, in main
    decls = pygccxml.parser.parse([input_header], config)
  File "/cvmfs/larsoft.opensciencegrid.org/products/pygccxml/v1_9_1b/lib/python3.7/site-packages/pygccxml-1.9.1-py3.7.egg/pygccxml/parser/__init__.py", line 51, in parse
  File "/cvmfs/larsoft.opensciencegrid.org/products/pygccxml/v1_9_1b/lib/python3.7/site-packages/pygccxml-1.9.1-py3.7.egg/pygccxml/parser/project_reader.py", line 264, in read_files
  File "/cvmfs/larsoft.opensciencegrid.org/products/pygccxml/v1_9_1b/lib/python3.7/site-packages/pygccxml-1.9.1-py3.7.egg/pygccxml/parser/project_reader.py", line 292, in __parse_file_by_file
  File "/cvmfs/larsoft.opensciencegrid.org/products/pygccxml/v1_9_1b/lib/python3.7/site-packages/pygccxml-1.9.1-py3.7.egg/pygccxml/parser/source_reader.py", line 356, in read_file
  File "/cvmfs/larsoft.opensciencegrid.org/products/pygccxml/v1_9_1b/lib/python3.7/site-packages/pygccxml-1.9.1-py3.7.egg/pygccxml/parser/source_reader.py", line 375, in read_cpp_source_file
  File "/cvmfs/larsoft.opensciencegrid.org/products/pygccxml/v1_9_1b/lib/python3.7/site-packages/pygccxml-1.9.1-py3.7.egg/pygccxml/parser/source_reader.py", line 324, in create_xml_file
RuntimeError: Error occurred while running CASTXML:  status:1
make[2]: *** [sbncode/sbncode/CAFAna/StandardRecord/Proxy/SRProxy.cxx] Error 1
make[1]: *** [sbncode/sbncode/CAFAna/StandardRecord/Proxy/CMakeFiles/StandardRecordProxy.dir/all] Error 2
```

**Comment by cjbackhouse** [comment]
oh, it's this again. Let me remember what the fix was before.

**Comment by cjbackhouse** [comment]
I just pushed the workaround I was using before. Are things ok now?

**Comment by wesketchum** [comment]
That appears to have worked, thanks!!

**Pull request merged**
