### PR TITLE
Feature/dmendez icarus cafweights

### PR DESCRIPTION
**Pull request by mendezdpatricia**
Edits to Icarus cafmaker for event weights.

### CODE REVIEW

**Comment by cjbackhouse** [comment]
The genieweight stuff looks fine. The sbnd fcls have (too many) variants with/without genieweight, with different readout lengths, with/without SCE etc, whereas here it looks like there's a single fcl and you've just turned on genieweight and changed the geometry unconditionally. I guess this is a icarus question about how things should be organized.

For the PROLOG issue, it would be good to figure out which of the headers actually caused the problem, and add the BEGIN/END_PROLOG there if appropriate.

**Comment by wesketchum** [comment]
@cjbackhouse so is this ok? If so can you do the review interface here and say approve? Trying to use these tools so long as they are useful.

**Review by cjbackhouse — APPROVED** [review]
This is all good. Comments were about potential future directions to tidy up.

**Review by etyley — APPROVED** [review]
I have nothing to add to what Chris has said

**Pull request merged**
