### PR TITLE
BNB Kaon Gen for SBND + Time of Flight Implementation

### PR DESCRIPTION
**Pull request by VCLanNguyen**
BNB Kaon Gen for SBND + Time of Flight Implementation for MeVPrtl

### CODE REVIEW

**Comment by VCLanNguyen** [comment]
Remake the PR since I broke the other branch on the PR. Already addressed comments by Gray on the other PR (https://github.com/SBNSoftware/sbncode/pull/317) 

As in the names: this includes Gen modules for BNB Kaon and Time of Flight.

**Comment by rodralva** [comment]
Looks good to me!

**Review by rodralva — APPROVED** [review]
Finally BNB data support +ToF added to develop

**Comment by VCLanNguyen** [comment]
Build errors seems to do with caf test, which this PR isn't related too. I'll start another build to check if the caf issue is resolved.

  | ◼ | nucosmics_caf_quick_test_sbndcode | (Problem:  Error in data production *** Scaled cpu usage 9345.181630000001 not in  3000.0:5000.0 range *** Memory usage 5244540.0 not in  2000000.0:4000000.0 range)
-- | -- | -- | --

**Comment by VCLanNguyen** [comment]
trigger build

**Comment by VCLanNguyen** [comment]
trigger build

**Comment by VCLanNguyen** [comment]
trigger build

**Comment by VCLanNguyen** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_64_01

**Review by gputnam — APPROVED** [review]
Looks good!

**Pull request merged**
