### PR TITLE
Updates to Calibration Workflows

### PR DESCRIPTION
**Pull request by gputnam**
Depends on https://github.com/SBNSoftware/sbnobj/pull/29.

Save more (per-wire) truth information in the Calibration NTuple-r. Clean up old notebooks. 

Include some python scripts that handle turning Calibration NTuple's into data-frames.

Get the track area hit maker to work with recent ICARUS-code.

### CODE REVIEW

**Review by PetrilloAtWork — CHANGES_REQUESTED** [review]
C++ part good in general; I did not attempt to review the Python notebook and code.
There is a possible bug, a couple of required changes and several suggestions, as usual.

---- 

As an exercise, I have tried to match my suggestions with the guideline document, for several reasons, including:
* I wanted to get a usage feeling.
* I wanted to see how the coverage of the guidelines is.
* The author can become familiar with the document and its content.
* The author can open a discussion on the guideline itself if he disagrees.

I also copied some code snippets from this review into the guideline. I expect to persist in this practice to make the examples in there more "real world". No judgement is implied in the choice.
Let's see how it goes...

**Comment by gputnam** [comment]
Oh! Good catch. I believe that code is old from this module being written just for SBND. Happy to fix it.

So -- I don't think that track trajectory points are guaranteed to reside in a cryostat. This is because the X position of tracks with hits outside the central readout window are set to non-fiducial points, unless their is a T0 correction.

What I have typically done is include a "Cryostat" configuration option that the user can set. I have done that in the above commit.

Also -- I believe I have addressed the other outstanding conversations.

**Review by PetrilloAtWork — APPROVED** [review]

**Comment by wesketchum** [comment]
@miquelnebot are we waiting on anything else for merging this in? I think not ... going to assign to you in the meantime to merge into next release.

**Comment by gputnam** [comment]
@miquelnebot resolved the conflict!

**Comment by PetrilloAtWork** [comment]
The solution pertains `icaruscode` itself (Clang details exactly what is needed), and there is not much that can be done in `sbncode`.
I am not sure of how this can be properly managed (@vitodb?). Maybe create a `feature/gputnam-calib-calo` in `icaruscode` with the fix? would this test pick it up?

**Comment by vitodb** [comment]
> The solution pertains `icaruscode` itself (Clang details exactly what is needed), and there is not much that can be done in `sbncode`. I am not sure of how this can be properly managed (@vitodb?). Maybe create a `feature/gputnam-calib-calo` in `icaruscode` with the fix? would this test pick it up?

I think this failure is completely independent from this PR.
This clang failure in icaruscode has been introduced when [ircruscode v09_35_01 has been cut](https://dbweb8.fnal.gov:8443/LarCI/app/ns:icarus/view_builds/index?offset=0&builds=icarus_ci%2F2923&builds=)
CI build `icarus_ci/2919` for `c7:prof` qualifier testing [icaruscode v09_35_00](https://dbweb8.fnal.gov:8443/LarCI/app/ns:icarus/build_detail/phase_details?build_id=icarus_ci/2919&platform=Linux%203.10.0-1160.31.1.el7.x86_64&phase=checkout_github&buildtype=slf7%20c7:prof) was OK,
while `icarus_ci/2923` for `c7:prof` qualifier testing [icaruscode v09_35_01](https://dbweb8.fnal.gov:8443/LarCI/app/ns:icarus/build_detail/phase_details?build_id=icarus_ci/2923&platform=Linux%203.10.0-1160.31.1.el7.x86_64&phase=checkout_github&buildtype=slf7%20c7:prof) failed with the same issue reported in this PR.

**Comment by vitodb** [comment]
> I am not sure of how this can be properly managed (@vitodb?). Maybe create a feature/gputnam-calib-calo in icaruscode with the fix? would this test pick it up?

More to the point, if `icaruscode` get fixed for this in develop branch, this PR will pick the change directly from there, as the CI uses develop branch for all repos if it is not told differently.
If a branch  `feature/gputnam-calib-calo` is made in icaruscode, then the trigger of a CI build of this PR to pick that branch requires a comment like
`trigger build  SBNSoftware/icaruscode@feature/gputnam-calib-calo`
or if a PR is made
`trigger build  SBNSoftware/icaruscode#PRnum`
 where `PRnum` is the PR number associated to the fix.

**Comment by PetrilloAtWork** [comment]
Pushed [SBNSoftware/icaruscode commit `9677f3ae`](https://github.com/SBNSoftware/icaruscode/commit/9677f3aedea2eb3ae29b9787f7dc21536e75c636). We'll see now...

**Comment by PetrilloAtWork** [comment]
trigger build SBNSoftware/sbnobj#29

**Comment by cjbackhouse** [comment]
@vitodb 
> If a branch feature/gputnam-calib-calo is made in icaruscode, then the trigger of a CI build of this PR to pick that branch requires a comment

Would it be a sensible feature to have CI automatically choose branches of the same name in other repositories, if not instructed differently? I think there are often changes spanning repositories, and using the same branch name in each is a common convention.

**Pull request merged**
