### PR TITLE
Update CAF Blinding Interface to Allow for Multiple Selections

### PR DESCRIPTION
**Pull request by gputnam**
Note -- this is not needed for the upcoming MCP. Depends on https://github.com/SBNSoftware/icaruscode/pull/537.

### CODE REVIEW

**Review by etworcester — APPROVED** [review]
Looks good to me. Did you check to make sure the output is identical?

**Comment by gputnam** [comment]
I think because of the use of random numbers I can't check if the files are identical. But I have checked that the energy is blinded as expected, that the POT is offset as expected, and that the prescaled files contain a subset of the total outputs.

**Comment by gputnam** [comment]
Found an issue with the POT -- please do not merge this PR quite yet.

**Comment by gputnam** [comment]
I don't think this is actually a good idea now -- closing.

**Pull request closed without merging**
