### PR TITLE
Feature/keng update genie w

### PR DESCRIPTION
**Pull request by Ooohu**
Update sbncode GENIE weight module, such that it can use knobs that are available in UBcode.

~~Note that the "NC" knob in the old sbncode is no longer available in GENIE v3.0.6 as a knob "name".
See that there is no std::string to call "kXSecTwkDial_NC" at line 98 of https://internal.dunescience.org/doxygen/GSyst_8h_source.html#l00141~~

Actually, "NC" knob was implemented in 2019; so, I add it back to the list now.
https://github.com/GENIE-MC/Reweight/blob/master/src/RwFramework/GSyst.h

Also needs to use an updated sbnobj module from PR 28: SBNSoftware/sbnobj#28

### CODE REVIEW

**Comment by wesketchum** [comment]
@mroda88 @Ooohu @mastbaum status on this?

**Comment by Ooohu** [comment]
It is updated!

**Comment by wesketchum** [comment]
OK, @mroda88, are you able to review?

**Comment by mroda88** [comment]
I'm on it

**Comment by wesketchum** [comment]
Thank you! 'Assigning' this to you so I have a handle of status of things. If you have requested changes, feel free to change the assignment.

**Comment by Ooohu** [comment]
Regarding to the isssue at GENIE CCQE-Strange events mentioned in https://github.com/GENIE-MC/Reweight/issues/12

The sbncode solution is to skip reweighting such events as implemented in: 
https://github.com/SBNSoftware/sbncode/blob/e9d0d3f03c4537097a4bac83016972936dc440ed/sbncode/SBNEventWeight/Calculators/CrossSections/GenieWeightCalc.cxx#L540-L542

ub-sbnd cross-validation is done by comparing output weights on the BhtBY knob (chosen arbitrarily) shown in slides 7 & 11 at:
https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=23427

**Review by mroda88 — APPROVED** [review]
All good and as discussed before

**Comment by mroda88** [comment]
trigger build

**Comment by Ooohu** [comment]
> ❌ CI build for ICARUS Failed at phase unit_test ICARUS on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/2927&builds=)
> 
> 🚨 For more details about the failed phase, check the [unit_test ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/2927&platform=Linux%203.10.0-1160.31.1.el7.x86_64&phase=unit_test&buildtype=slf7%20e20:prof)
> 
> parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/13274&builds=)

It contains error from the `DetSim` directory?: 
```
2222: In file included from /scratch/workspace/icarus_ci/label_exp/SLF7/label_exp2/swarm/ICARUS/srcs/icaruscode/icaruscode/TPC/Simulation/DetSim/SimWireICARUS_module.cc:62:
2223: /scratch/workspace/icarus_ci/label_exp/SLF7/label_exp2/swarm/ICARUS/srcs/icaruscode/icaruscode/TPC/Simulation/DetSim/tools/IGenNoise.h:24:5: error: class 'PlaneID' was previously declared as a struct [-Werror,-Wmismatched-tags]
2224:     class PlaneID;
2225:     ^
2226: /cvmfs/larsoft-ib.opensciencegrid.org/LArSoft/LArSoft_slf7_c7_prof_20211105_023019/localProducts_LArSoft_LArSoft_lar_ci_c7_prof/larcoreobj/v09_03_01/include/larcoreobj/SimpleTypesAndConstants/geo_types.h:472:10: note: previous use is here
2227:   struct PlaneID: public TPCID {
2228:          ^
2229: /scratch/workspace/icarus_ci/label_exp/SLF7/label_exp2/swarm/ICARUS/srcs/icaruscode/icaruscode/TPC/Simulation/DetSim/tools/IGenNoise.h:24:5: note: did you mean struct here?
2230:     class PlaneID;
2231:     ^~~~~
2232:     struct
2233: 1 error generated.
2234: [1323/1530] Building CXX object icaruscode/icaruscode/TPC/Simulation/DetSim/CMakeFiles/icaruscode_TPC_Simulation_DetSim_SimReadoutBoardICARUS_module.dir/SimReadoutBoardICARUS_module.cc.o
2235: FAILED: 
```

**Comment by vitodb** [comment]
> > x CI build for ICARUS Failed at phase unit_test ICARUS on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/2927&builds=)
> > rotating_light For more details about the failed phase, check the [unit_test ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/2927&platform=Linux%203.10.0-1160.31.1.el7.x86_64&phase=unit_test&buildtype=slf7%20e20:prof)
> > parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/13274&builds=)
> 
> It contains errors from the `class PlaneID` in `/scratch/workspace/icarus_ci/label_exp/SLF7/label_exp2/swarm/ICARUS/srcs/icaruscode/icaruscode/TPC/Simulation/DetSim/SimWireICARUS_module.cc`:
> 
> ```
> 2222: In file included from /scratch/workspace/icarus_ci/label_exp/SLF7/label_exp2/swarm/ICARUS/srcs/icaruscode/icaruscode/TPC/Simulation/DetSim/SimWireICARUS_module.cc:62:
> 2223: /scratch/workspace/icarus_ci/label_exp/SLF7/label_exp2/swarm/ICARUS/srcs/icaruscode/icaruscode/TPC/Simulation/DetSim/tools/IGenNoise.h:24:5: error: class 'PlaneID' was previously declared as a struct [-Werror,-Wmismatched-tags]
> 2224:     class PlaneID;
> 2225:     ^
> 2226: /cvmfs/larsoft-ib.opensciencegrid.org/LArSoft/LArSoft_slf7_c7_prof_20211105_023019/localProducts_LArSoft_LArSoft_lar_ci_c7_prof/larcoreobj/v09_03_01/include/larcoreobj/SimpleTypesAndConstants/geo_types.h:472:10: note: previous use is here
> 2227:   struct PlaneID: public TPCID {
> 2228:          ^
> 2229: /scratch/workspace/icarus_ci/label_exp/SLF7/label_exp2/swarm/ICARUS/srcs/icaruscode/icaruscode/TPC/Simulation/DetSim/tools/IGenNoise.h:24:5: note: did you mean struct here?
> 2230:     class PlaneID;
> 2231:     ^~~~~
> 2232:     struct
> 2233: 1 error generated.
> 2234: [1323/1530] Building CXX object icaruscode/icaruscode/TPC/Simulation/DetSim/CMakeFiles/icaruscode_TPC_Simulation_DetSim_SimReadoutBoardICARUS_module.dir/SimReadoutBoardICARUS_module.cc.o
> 2235: FAILED: 
> ```

that failure was for CI build [icarus_ci/2925](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci%2F2925&builds=) testing `sbndcode PR 184`.
This PR has failure for [testFHiCLfiles_icarus.sh](https://dbweb8.fnal.gov:8443/LarCI/app/ns:ICARUS/build_detail/test_details?build_id=icarus_ci/2927&platform=Linux%203.10.0-1160.31.1.el7.x86_64&buildtype=slf7%20e20:prof&phase=unit_test&test=testFHiCLfiles_icarus.sh) unit test, its [log](https://dbweb8.fnal.gov:8443/LarCI/app/ns:icarus/storage/docs/2021/11/08/testFHiCLfiles_icarus.sh.log) seems to suggest a FHiCL file is missing
```
70: terminate called after throwing an instance of 'cet::exception'
71:   what():  ---- search_path BEGIN
72:   Can't find file "eventweight_genie3_sbn_A.fcl"
73: ---- search_path END
74: 
75: /scratch/workspace/icarus_ci/label_exp/SLF7/label_exp2/swarm/ICARUS/build_slf7.x86_64/icaruscode/test/fcl/testFHiCLfiles_icarus.sh.d/testFHiCLfiles.sh: line 221: 49241 Aborted                 (core dumped) $fhicldump --quiet "${Options[@]}" --config "$FHiCLpath"
76: ERROR: File '/scratch/workspace/icarus_ci/label_exp/SLF7/label_exp2/swarm/ICARUS/build_slf7.x86_64/icaruscode/job/cafmakerjob_icarus.fcl' failed verification (code: 134).
[...]
```

**Comment by Ooohu** [comment]
I update the "eventweight_genie3_sbn_A.fcl" to the new version to avoid "missing FHiCL" errors. This file would be identical to "genie_eventweight.fcl", which is the one we should be using.

**Comment by Ooohu** [comment]
trigger build

**Comment by vitodb** [comment]
> @vitodb do I understand correctly ICARUS CI fails were due to other ICARUS PRs? @wesketchum do you want to give the OK @Ooohu requested for the .fcl change?

@miquelnebot the ICARUS failure for c7 builds is due to ICARUS PR, but the ICARUS failure for unit tests on slf7 is possibly due to issue in this PR

**Comment by Ooohu** [comment]
Update the FHiCLs for CAF.

**Comment by Ooohu** [comment]
@vitodb  @miquelnebot  Hello, can you help me to trigger build again? Thanks!
trigger build

**Comment by PetrilloAtWork** [comment]
trigger build SBNSoftware/sbnobj@feature/keng_SBNEventWgt_FHiCLUpdates

**Comment by PetrilloAtWork** [comment]
Oops...it looks like we were doing things at the same time.
I have triggered a build to use the fix in `icaruscode` with the new naming, while you reverted the naming to work with the _current_ `icaruscode`. I.e., probably the test I started will fail for a reason mirror of the previous failure.

**Comment by vitodb** [comment]
@PetrilloAtWork @Ooohu if it is the case I can abort the current CI build, so you can trigger a new one with the proper list of branches

**Comment by PetrilloAtWork** [comment]
Is that legal in Illinois? if so, go ahead.

**Comment by PetrilloAtWork** [comment]
@vitodb it seems the test is recompiling LArSoft. Is that true? if so, why did the fast-forward not kick in?

**Comment by vitodb** [comment]
> > I can abort the current CI build
> 
> Is that legal in Illinois? if so, go ahead.

For this we are good to go, I just did!

> @vitodb it seems the test is recompiling LArSoft. Is that true? if so, why did the fast-forward not kick in?

I think this is because a new LArSoft release has just been pushed out.
Because the CI doesn't have a LArSoft develop code built on its CMFS instance matching the new LArSoft release, it went ahead and started building it.

**Comment by PetrilloAtWork** [comment]
trigger build

**Comment by Ooohu** [comment]
Sorry, there was a small typo that triggers the failure in e20 CI builds. Now it is fixed!

**Comment by Ooohu** [comment]
trigger build

**Comment by PetrilloAtWork** [comment]
trigger build

**Comment by Ooohu** [comment]
I am still testing the outputs; Still need to fix some lines of FHiCL under `SBNEventWeight/jobs` directory.

**Comment by Ooohu** [comment]
Finish editing FHiCL files and have verified `cafmakerjob_sbnd_sce_genie_and_fluxwgt.fcl` is fully working as expected.

**Comment by henrylay97** [comment]
@Ooohu @wesketchum @jzennamo so with this PR the fcl used to run production CAFs no longer exists. I assume that the file used will be `cafmakerjob_sbnd_sce_genie_and_fluxwgt.fcl` and that this is the file that you would like the CI to test?

**Comment by wesketchum** [comment]
@henrylay97, I think the exact file to test may get changed with  https://github.com/SBNSoftware/sbncode/issues/170, so should probably track those changes there ...

**Comment by henrylay97** [comment]
thanks @wesketchum

**Pull request merged**
