### PR TITLE
Introduce Barycenter Flash Match

### PR DESCRIPTION
**Pull request by JackSmedley**
sbncode updates - Add barycenter flash match objects into CAFmaker and shift the data time variables to beam reference

Associated Pull Requests ---
sbnobj PR- https://github.com/SBNSoftware/sbnobj/pull/99
sbnanaobj PR- https://github.com/SBNSoftware/sbnanaobj/pull/111
sbncode PR- https://github.com/SBNSoftware/sbncode/pull/392
icaruscode PR- https://github.com/SBNSoftware/icaruscode/pull/641

### CODE REVIEW

**Review by PetrilloAtWork — COMMENTED** [review]
Approved with comments, but pending SBNSoftware/icaruscode#641 .

**Review by PetrilloAtWork — COMMENTED** [review]
Approved with my cheers.

**Review by PetrilloAtWork — APPROVED** [review]
Approved with my cheers.

**Review by aheggest — APPROVED** [review]
Looks good to me!

**Pull request merged**
