### PR TITLE
Feature/jdyer_KDIFonlyOption

### PR DESCRIPTION
**Pull request by jamiecd**
I made changes to enable generation of Higgs Portal Scalar events only from kaons decaying in flight.

### CODE REVIEW

**Comment by gputnam** [comment]
Just one comment on this PR -- I implemented the KDAR option as only selecting for KDAR at the absorber (hence the z position cut). There will also be a fraction of KDAR from the decay pipe, which this implementation will allow through. But that shouldn't stop approval of this PR -- it's up to Jamie what she wants the behavior of the KDIF option to be.

**Comment by jamiecd** [comment]
Thanks Gray, good point! I'll exclude the decay-pipe KDAR. I just made the needed change.

**Comment by jamiecd** [comment]
@miquelnebot I have made a few more commits - some that update the code and one that I believe will resolve the conflict above. Can you try to merge the code again?

(@grayputnam - unless this is not the right branch to be merging changes to?)

**Comment by gputnam** [comment]
There was a git conflict induced by this PR alongside https://github.com/SBNSoftware/sbncode/pull/243/files. I've resolved the conflict to include the changes from both PR's. This should be good to go now.

**Review by gputnam — APPROVED** [review]

**Pull request merged**
