### PR TITLE
Feature/evtwgt_cosmic

### PR DESCRIPTION
**Pull request by cjbackhouse**
There are several different small fixes for cosmics/geniewgt/cafs in here.

Some discussed here https://github.com/SBNSoftware/sbncode/issues/107
and the final commit with the fcl changes in the meeting today. I don't think there's an associated issue.

### CODE REVIEW

**Comment by cjbackhouse** [comment]
I didn't do anything to the icarus cafmaker fcl. I think whether that wants to be split or not is up for discussion.

I tested that `lar -c cafmakerjob_sbnd_3drift_sce_runfmatch.fcl /pnfs/sbnd/mc/reco2/artroot/official/MCP2020A/prodcorsika_proton_intime_filter/sbndcode/v09_09_00_01/run_number/00/00/00/13/subrun_number/00/00/00/42/reco2-68cbb816-750b-4ec1-847a-ecec01877cfb.root` runs. It also works with the `_geniewgt` suffix, though wastes some effort setting up the calculators. I think that means that in principle icarus could get away with one fcl.

**Comment by gputnam** [comment]
This looks good to me, except I think @etyley had suggested that the SystWeightLabel be set to "" by default (in CAFMaker.fcl) and overridden to "genieweight" for the specific configuration that needs it.

**Review by gputnam — CHANGES_REQUESTED** [review]
see comment above.

**Comment by cjbackhouse** [comment]
Done

**Review by gputnam — APPROVED** [review]

**Comment by gputnam** [comment]
Great! Thanks.

**Pull request merged**
