### PR TITLE
Feature/lnguyen caloskimmer

### PR DESCRIPTION
**Pull request by VCLanNguyen**
- Edit the fcl file parameters: median dQdx cut for sbnd 
- Changed the name of the calorimetry module
These files will be used to produce the ntuples for the Calibration workshop.

### CODE REVIEW

**Comment by wesketchum** [comment]
@gputnam i you're able to help review, that would be great.

**Comment by VCLanNguyen** [comment]
This PR needs to be merged together for the sbndcode PR below:
[https://github.com/SBNSoftware/sbndcode/pull/173](url)

**Review by gputnam — CHANGES_REQUESTED** [review]
Configuration changes look good! 

However, the two jupyter notebooks both seem to have binary stuff (i.e. plots) in them. I would recommend they be removed from the PR (or at least those plots stripped out).

**Comment by VCLanNguyen** [comment]
> 
> 
> Configuration changes look good!
> 
> However, the two jupyter notebooks both seem to have binary stuff (i.e. plots) in them. I would recommend they be removed from the PR (or at least those plots stripped out).

@grayputnam I think I've cleaned out the plots in the jupyter notebooks now. If it's a lot for the PR maybe I can remove the notebooks?

**Comment by gputnam** [comment]
Thanks! All set then.

**Review by gputnam — APPROVED** [review]

**Pull request merged**
