### PR TITLE
Accommodate breaking changes for geometry refactoring

### PR DESCRIPTION
**Pull request by knoepfel**
Accommodate changes from:

- https://github.com/LArSoft/larcoreobj/pull/19
- https://github.com/LArSoft/larcorealg/pull/37

----

**N.B.**: This PR should not be merged until the above PRs have been merged into a LArSoft release.

### CODE REVIEW

**Comment by knoepfel** [comment]
@miquelnebot, the above PRs have been included in the `v10_00_00rc_br` LArSoft branches, but they have not been merged into mainline development yet.  Once LArSoft 10 is tagged, this PR can be merged (modulo conflicts, which I'll need to resolve).

**Comment by ibsafa** [comment]
@knoepfel can you please comment on this? this PR is now quite far behind and would need resolving conflicts. is this still required? Also, I just tried compiling sbncode with v10_01_00 and it works without this PR so I was confused why that would work.

**Comment by ibsafa** [comment]
@knoepfel Hi Kyle, can you please let us know how we need to proceed? We're trying to release a new sbncode version that depends on larsoft v10_YY_ZZ and at the moment I cannot move forward without your input on this PR. thank you!

**Comment by knoepfel** [comment]
@ibsafa, I've updated the PR to no longer conflict with the HEAD of `develop`.  Two things to keep in mind:

1. I needed to adjust the Supera code (see https://github.com/DeepLearnPhysics/Supera/pull/22).  Once the DeepLearning folks merge that PR, you'll need to update the Supera submodule in this repository.
2. You'll need to adjust the version of LArSoft to v10 in the UPS `product_deps` file.

**Pull request merged**
