### PR TITLE
Improvements and corrections to the Simple Flash Matcher

### PR DESCRIPTION
**Pull request by ikatza**
Several improvements to the Simple Flash Match code, a mixture of corrections, syntax enhancements and new features.

New features:
 -------------

- New metric PE to Charge ratio, this aids to prevent matching against the late part of a flash
- Correction to flash_ratio formula for SBND
- Drop additional, incorrect, absolute value in score term computation
- Compute and store the charge and flash widths
- Compute and store flash kurtosis in the tree
- Compute the fractional time when a flashes reads a given fraction of the total PE, also useful to determine if flash is from late light
- Add drift distance corrections that use flash time
- Add support to use other OpHit times: PeakTime, RisingTime and StartTime
- Force the flash matching to look for a minimum amount of flashes in the beam spill window
- Automise the fitting of the polynomials that are used to make corrections to the flashY and flashZ
- Store coefficients of polynomials in metrics file 
- Many new variables stored in fm tree used for developing and diagnose
- Several new objects to encapsulate variables, avoid repetition and improve syntax
- Reduce verbosity of module
- Create and use a 3D voxelised map of each metric, that takes into account the X,Y,Z coordinates of a slice of charge to score the association with a flash.

This is the main PR, the other PR that have to be used along with this:
https://github.com/SBNSoftware/sbnanaobj/pull/80
https://github.com/SBNSoftware/sbnobj/pull/69
https://github.com/SBNSoftware/sbndcode/pull/303
https://github.com/SBNSoftware/icaruscode/pull/462

~~The new metrics files have to be included to sbnd_data and icarus_data before this PR can be tested. I will comment here when this PR is ready to be tested.~~
Metrics files have now been updated.

### CODE REVIEW

**Comment by ikatza** [comment]
Hi @miquelnebot, I have updated the metrics file for ICARUS, not yet for SBND. Can you please issue the trigger build again for `icaruscode`?

The update to `sbnd_data` will come live tomorrow afternoon.

**Comment by ikatza** [comment]
I have updated the repos to the current version, merging develop onto them.

- `sbndcode` points to the new version of data that is already reachable, and can be tested.
- `icaruscode` doesn't yet point to the new data, as this hasn't been propagated to cvmfs. It is not ready to test.

**Comment by ggamezdiego** [comment]
The corrections/improvements look good to me by eye. I would ask for some validation tests, but I know that PDS-reco2 is not yet included (right?). I think it would be useful in any case to see the results of the modifications in terms of performance to be sure all looks fine

**Comment by ikatza** [comment]
I believe you're right @ggamezdiego, the validation won't test these changes. They'll only test that it builds and that it doesn't go overboard with resources.

The `icarus_data` https://cdcvs.fnal.gov/redmine/projects/icarus_data/repository repository still needs to be tagged and distributed on cvmfs to be able to catch the latest metrics file. 

The `sbndcode` repo is ready to be tested.

To demonstrate performance I have some plots, would you like to wait for a presentation at a meeting before accepting the changes @ggamezdiego?

**Comment by ggamezdiego** [comment]
Thanks @ikatza! I think that would be useful in the absence of CI tests. You could present in a next SBN-PDS meeting. But probably it would be important to show results for both SBND and ICARUS. When do you think you will be ready? What do you think @amenegol ?

**Comment by ggamezdiego** [comment]
Our next one would be in October 28 Friday (10am CT). Would that work for you, or is too late?

**Comment by lynnt-uchicago** [comment]
Hi Iker!! I just wanted to check, this PR doesn't include using the flash time from OpFlashes and still only uses OpHit information correct?

**Comment by ikatza** [comment]
> Our next one would be in October 28 Friday (10am CT). Would that work for you, or is too late?

It's fine by me, but I advertised to some people on ICARUS that this PR would be helpful to have for their data processing. I don't really know the time line for that, but if they're planning to start before the 28th it might be worth to consider another review mechanism.


> Hi Iker!! I just wanted to check, this PR doesn't include using the flash time from OpFlashes and still only uses OpHit information correct?

Hi Lynn, I didn't include `OpFlashes`, so it's still is my definition of flash time, but I added some support to use the other times from ophits (`RiseTime, PeakTime` and `StartTime`).

**Comment by ggamezdiego** [comment]
@amenegol, what do you think?

**Review by ggamezdiego — APPROVED** [review]

**Comment by ikatza** [comment]
For ICARUS the new metrics are already in the repository: 
https://cdcvs.fnal.gov/redmine/projects/icarus_data/repository?utf8=✓&rev=master

However I'm not sure if they have been updated to cvmfs.

**Comment by ikatza** [comment]
The failure to build `sbndcode` doesn't seem to be related to this PR:

```
912: CMake Error at /cvmfs/larsoft.opensciencegrid.org/products/cetmodules/v3_19_02/Modules/CetMakeLibrary.cmake:250 (target_link_libraries):
913:   Target "sbndcode_Trigger_CRTArtdaqFragmentProducer_module" links to:
914: 
915:     artdaq_core::artdaq-core_Data_Artdaq_fragmentNameHelper
916: 
917:   but the target was not found.  Possible reasons include:
918: 
919:     * There is a typo in the target name.
920:     * A find_package call is missing for an IMPORTED target.
921:     * An ALIAS target is missing.
```

As for the failures in `icaruscode`, I suspect is because the new version of `icarus_data/FlashMatch/fm_metrics_icarus.root` hasn't been distributed.

**Comment by ikatza** [comment]
I've updated all of the repositories to be in line with `v09_63_00`, fixed merge conflicts and `icarus_data` has now the metrics file.

**Comment by ikatza** [comment]
The failures do not seem to be related to this PR, I reckon they're related to yesterday's maintenance. Could you please try again @miquelnebot?

**Comment by ikatza** [comment]
The SBND test failed because I messed up the merge to update the code, sorry. I've updated the version of `sbnd_data` and it's now fixed.

The ICARUS test failure is due to some conflicting dependency, unrelated to this PR. I've updated my branch to be synchronised with develop, and re-updated the version of `icarus_data` as it was pushed back.

Both repos work on my testing area now, but I do need to include `icarusalg` and `icarus_signal_processing` to my build to be able to compile.

**Comment by ikatza** [comment]
Finally!

The differences in SBND cafs are expected, as I added new variables. I don't think the rest of warnings are related to these PRs, certainly nothings related to `gen, g4, detsim` or `reco0/reco1` as I didn't change anything in those stages.

**Pull request merged**
