### PR TITLE
Feature/etw icarusblinding

### PR DESCRIPTION
**Pull request by etworcester**
Two things - this fixes yet another bug in the output files - this time the flat cafs were corrupted, which has been fixed with this update. The second thing is to fill a flag in the header which labels whether a file is blinded/prescaled or not. The second thing depends on sbnanaobj PR #78, which adds that flag to SRHeader.

### CODE REVIEW

**Review by jacoblarkin — APPROVED** [review]
Look good. Tested on ICARUS data and it appears to be working.

**Comment by wesketchum** [comment]
@cerati and I marked ready for release on this, but we should verify if these CI tests should be passing/what the issue is there

**Comment by etworcester** [comment]
trigger build https://github.com/SBNSoftware/sbnanaobj/pull/78

**Comment by etworcester** [comment]
@miquelnebot the CI test doesn't seem to be picking up the sbnanaobj PR correctly - both Jacob and I confirmed that we can build on gpvms, but the CI build fails complaining about a variable that doesn't exist, which is exactly the variable added in the sbnanobj PR. Any suggestions?

**Pull request merged**
