### PR TITLE
Improvements to Simple Flash Match

### PR DESCRIPTION
**Pull request by ikatza**
I'm opening this PR as requested anticipating the split of `sbncode/sbnana`. 

**Summary of improvements**
-  Store the global X coordinate of charge on the tree, fix bug folding global X to drift distance.
- Create a new metric for ICARUS, the ratio of PEs from PMTs in one side and the other.
- Use XARAPUCAS in SBND
- Compute an estimate of the drift distance from light `hypo_x`
- Store partial scores on the tree
- Assign negative scores when conditions are not met
- Improved logging and messages
-  Overall maintenance, encapsulation, renaming, cleaning of code

Ready to be merged to `develop`, but it also requires corresponding PRs in `sbndcode`, `sbnd_data`, `icaruscode` and `icarus_data`.

Look at [20861-v1](https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=20861) for further details.

### CODE REVIEW

**Comment by wesketchum** [comment]
Thanks a lot Iker. Agree we should not merge this to develop yet, but this should be pretty easy to keep this branch. We may assign a new name to it and delete this branch and ask you to use the new one going ahead to try to avoid history issues, so please do make sure it's all pushed by by Friday (if not already so).

**Comment by cjbackhouse** [comment]
Since this only touches the FlashMatch/ directory, which is staying in sbncode and won't be changed at all in the split, I think that there's actually nothing we have to do here, and this branch will be completely fine to merge at some point afterwards.

**Comment by wesketchum** [comment]
I'm closing this request, as I think we've closed the loop on the updates.

**Comment by ikatza** [comment]
I'm reopening this one, now that I'm finished with it.

Will edit the top comment.

**Comment by ikatza** [comment]
The other repos PR:
https://github.com/SBNSoftware/icaruscode/pull/124
https://github.com/SBNSoftware/sbndcode/pull/85

New metrics for ICARUS are in this branch: 
https://cdcvs.fnal.gov/redmine/projects/icarus_data/repository?utf8=✓&rev=feature%2Ficaza_fm_improvements

I'll coordinate with SBND release manager so those metrics are also updated.

**Comment by wesketchum** [comment]
Thanks @ikatza. Is there a recent presentation/description of the updates? Would be nice to see (and see linked here), but don't think that's blocking unless @mstancar thinks necessary.

@mstancar , if you could review that would be much appreciated.

@SFBayLaser and @pgreen135 , if you can coordinate new metrics and etc. that would be much appreciated. Sounds like next week's release would be a reasonable target (don't want to delay this week's, since we had no release last week).

**Review by mstancar — APPROVED** [review]

**Comment by ikatza** [comment]
As requested I presented at the ICARUS Optical Reconstruction Meeting: [20996](https://sbn-docdb.fnal.gov/cgi-bin/private/ShowDocument?docid=20996)

**Pull request merged**
