### PR TITLE
Saving GENIE tree to caf [develop]

### PR DESCRIPTION
**Pull request by jedori0228**
This is a copy (cherry-picked) of https://github.com/SBNSoftware/sbncode/pull/426 against develop.

This PR requires https://github.com/SBNSoftware/sbnanaobj/pull/128

### CODE REVIEW

**Comment by ibsafa** [comment]
trigger build

**Comment by ibsafa** [comment]
@PetrilloAtWork I see that you've already approved this PR for the NuMI branch. I assume that means it's also fine to move ahead with the changes to develop?

**Comment by jedori0228** [comment]
> trigger build

Hi @ibsafa! Just checked the error log and it was due to missing https://github.com/SBNSoftware/sbnanaobj/pull/128

**Comment by ibsafa** [comment]
> > trigger build
> 
> Hi @ibsafa! Just checked the error log and it was due to missing [SBNSoftware/sbnanaobj#128](https://github.com/SBNSoftware/sbnanaobj/pull/128)

Oh, sorry! I will add that and trigger another one.

**Comment by ibsafa** [comment]
trigger build https://github.com/SBNSoftware/sbnanaobj/pull/124

**Comment by ibsafa** [comment]
trigger build https://github.com/SBNSoftware/sbnanaobj/pull/128

**Comment by ibsafa** [comment]
trigger build SBNSoftware/sbnanaobj/#128

**Pull request merged**
