### PR TITLE
Add CRTPMT Matching variables to CAFs (production)

### PR DESCRIPTION
**Pull request by aheggest**
This is a duplicate of PR #353 for production release

### CODE REVIEW

**Comment by aheggest** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_72_00 SBNSoftware/sbndaq-artdaq-core@v01_06_00of0 SBNSoftware/sbnanaobj#97 SBNSoftware/sbnobj#88 SBNSoftware/icaruscode#600

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_72_00 SBNSoftware/sbnanaobj#97 SBNSoftware/sbndaq-artdaq-core@v1_06_00of0 SBNSoftware/sbnobj#88 SBNSoftware/icaruscode#600 SBNSoftware/icarus_signal_processing@v09_63_00_02 SBNSoftware/icarusalg@v09_72_00 SBNSoftware/icarusutil@v09_66_02

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_72_00 SBNSoftware/sbnanaobj#97 SBNSoftware/sbndaq-artdaq-core@v1_06_00of0 SBNSoftware/sbnobj#88 SBNSoftware/icaruscode#600 SBNSoftware/icarus_signal_processing@v09_63_00_02 SBNSoftware/icarusalg@v09_72_00 SBNSoftware/icarusutil@v09_66_02 SBNSoftware/sbndcode@v09_72_00 SBNSoftware/sbndutil@v09_72_00

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_72_00 SBNSoftware/sbnanaobj#97 SBNSoftware/sbndaq-artdaq-core@v1_06_00of0 SBNSoftware/sbnobj#88 SBNSoftware/icaruscode#600 SBNSoftware/icarus_signal_processing@v09_63_00_02 SBNSoftware/icarusalg@v09_72_00 SBNSoftware/icarusutil@v09_66_02 SBNSoftware/sbndcode@v09_72_00 SBNSoftware/sbndutil@v09_72_00

**Pull request merged**
