### PR TITLE
CNN scores with michel scores around pfp endpoints

### PR DESCRIPTION
**Pull request by wjdanswjddl**
CNN predicted scores for PFPs, complementary to existing pfp BDT trackscore
- when running the module, option to get PFP track/shower/noise score  or the Michel score around PFP end is both configurable -- you can run either one, both, or none. 
- PFP track/shower/noise score is the "average" of the scores of associated clusters -- details explained with the comment in the function
- Michel score around PFP end is now available -- size of the area to scan is configurable.
- CAF objects are available.

This PR is dependent on [sbnobj PR #97](https://github.com/SBNSoftware/sbnobj/pull/97), [sbnanaobj PR #108](https://github.com/SBNSoftware/sbnanaobj/pull/108).

### CODE REVIEW

**Comment by wjdanswjddl** [comment]
@miquelnebot I fixed the CMakeLists file that caused the fatal error in the build

**Comment by wjdanswjddl** [comment]
updated CMakeLists to deal with clang build of tensorflow not being provided

**Review by absolution1 — APPROVED** [review]
Approved!
Apologies, I did not see this come through.

**Comment by fjnicolas** [comment]
CI built in SBNSoftware/sbndcode#386

**Pull request merged**
