### PR TITLE
testing CI GitHub Integration

### PR DESCRIPTION
**Pull request by vitodb**
Testing Jenkins CI integration with GitHub
This PR is not intended to be merged into icaruscode.
This is intended only to test Jenkins CI integration with GitHub

### CODE REVIEW

**Comment by vitodb** [comment]
trigger build

**Comment by vitodb** [comment]
trigger build LArSoft/larevt#11,SBNSoftware/sbndcode#108

**Comment by vitodb** [comment]
trigger build

**Comment by vitodb** [comment]
trigger build SBNSoftware/icaruscode#178

**Comment by wesketchum** [comment]
Closing ... as It hink testing is done?

**Pull request closed without merging**
