### PR TITLE
adding missing geant processes to CAF

### PR DESCRIPTION
**Pull request by jzennamo**
Requires: https://github.com/SBNSoftware/sbnanaobj/pull/36

### CODE REVIEW

**Comment by cjbackhouse** [comment]
Does this also need a piece in `sbnanaobj` to add the appropriate enum values?

**Comment by jzennamo** [comment]
@cjbackhouse on its way

**Comment by jzennamo** [comment]
Thanks for pointing that out!

**Comment by jzennamo** [comment]
Requires: https://github.com/SBNSoftware/sbnanaobj/pull/36

**Comment by jzennamo** [comment]
@wesketchum proposes making the enum for kUNKNOWN to be very large such that in future usage this becomes somewhat backward compatible. He's testing and will push a fix

**Review by cjbackhouse — APPROVED** [review]

**Comment by cjbackhouse** [comment]
Yes, I think zero would have been the right choice for "unknown" originally, but that ship has sailed. 999 or so sounds reasonable to me.

**Review by PetrilloAtWork — APPROVED** [review]
Approved, although I have a concern with the companion pull request, which I will vent elsewhere.

**Pull request merged**
